from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.index, name='index'),
    path('mapa', views.mapa, name='mapa'),
    path('ancestries', views.ancestries, name='ancestries'),
    path('common', views.common, name='common'),
    path('uncommon', views.uncommon, name='uncommon'),
    path('rare', views.rare, name='rare'),
    path('universal', views.universal, name='universal'),
    path('alchfeats', views.alchfeats, name='alchfeats'),
    path('alchitens', views.alchitens, name='alchitens'),
    path('grafts', views.grafts, name='grafts'),
    path('symbionts', views.symbionts, name='symbionts'),
    path('alchemy', views.alchemy, name='alchemy'),
    path('campaign', views.campaign, name='campaign'),
    path('characters', views.characters, name='characters'),
    path('hall', views.hall, name='hall'),
    path('logs', views.logs, name='logs'),
    path('mudancas', views.mudancas, name='mudancas'),
    path('magicarquetypes', views.magicarquetypes, name='magicarquetypes'),
    path('magicitens', views.magicitens, name='magicitens'),
    path('newpowers', views.newpowers, name='newpowers'),
    path('magic', views.magic, name='magic'),
    path('techcreations', views.techcreations, name='techcreations'),
    path('techfeats', views.techfeats, name='techfeats'),
    path('techitens', views.techitens, name='techitens'),
    path('tech', views.tech, name='tech'),
    path('cosmos', views.cosmos, name='cosmos'),
    path('entities', views.entities, name='entities'),
    path('faecourts', views.faecourts, name='faecourts'),
    path('herogods', views.herogods, name='herogods'),
    path('oldgods', views.oldgods, name='oldgods'),
    path('gods', views.gods, name='gods'),
    path('kingdoms', views.kingdoms, name='kingdoms'),
    path('cenario', views.cenario, name='cenario'),
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)